services:
  - type: web
    name: sentinelpy-backend
    env: python
    buildCommand: "pip install uv && uv sync"
    startCommand: "cd backend && alembic upgrade head && gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./sentinelpy.db
      - key: APP_TITLE
        value: SentinelPy
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: http://localhost:5173